### ISSUE TITLE
Try to automate GP & Github releases via Github Actions

### ISSUE THREAD

**Issue by vodemn** [vodemn/m3_lightmeter#61]
Currently to create a new release on GP and Github I need to manually run a `Build prod .aab & .apk` action, download attached artefacts and create 2 separate releases with the same release notes. Probably it can be at least partially automated.

### Common
- [x] Find a way to pass release notes to the Github Actions workflow (#101)

### Github release
- [x] Update version in pubspec from GitHub actions (#84)
- [x] Create Github release from Github actions (#84)
- [x] Delete apk artefact after Github release has been created (#96)

### Google Play release
- [x] Try using `buildTypes.release.ndk.debugSymbolLevel 'FULL'` (#79)
- [x] Zip merged_native_libs only for arm64-v8a & armeabi-v7a (#96)
- [x] Create Google Play release from Github actions (#101)
- [x] Delete aab artefact after Google Play release has been created (#96)

### App Store release
TBD
